### ISSUE TITLE
 [ERROR] Hakyll.Core.UnixFilter.unixFilterWith: sassc ./sass/app.sass gave exit code 1

### ISSUE THREAD

**Issue by luckypoem** [ThibaudDauce/thibaud-dauce#4]
root@AR:/usr/local# git clone https://github.com/ThibaudDauce/thibaud-dauce thibaud.dauce.fr
root@AR:/usr/local# cd thibaud.dauce.fr
root@AR:/usr/local/thibaud.dauce.fr# ghc --make thibaud.hs
root@AR:/usr/local/thibaud.dauce.fr# ./thibaud rebuild
it shows:
...
 [ERROR] Hakyll.Core.UnixFilter.unixFilterWith: sassc ./sass/app.sass gave exit code 1
root@AR:/usr/local/thibaud.dauce.fr# gem install sassc
root@AR:/usr/local/thibaud.dauce.fr# which sassc
/usr/local/bin/sassc
root@AR:/usr/local/thibaud.dauce.fr# ./thibaud rebuild

i still encounter:
 [ERROR] Hakyll.Core.UnixFilter.unixFilterWith: sassc ./sass/app.sass gave exit code 1

how to fix it?

**Comment by ThibaudDauce** [comment]
Hi,

You need to install `sassc` and have it in your `$PATH`. If you're using Ubuntu, I think you just need to run `apt install sassc`.

I also encourage you to use [Stack](https://docs.haskellstack.org/en/stable/README/) to build the project :-)

**Comment by ThibaudDauce** [comment]
You need to install NPM dependencies (to download the Bulma CSS framework) with `npm install` or `yarn` in the root directory.

I think it should fix the problem…

**Comment by luckypoem** [comment]
i see.
i used nvm to install nodejs.after logining vps,i forgot to run "nvm use 7.4.0",so i ran "npm install",there is no reaction.now all is ok.

**Comment by ThibaudDauce** [comment]
Cool! Do not hesitate to send me a link if you build something with this repo :-)
